"""
Data Models for Order Management System

Defines all data structures used in the OMS:
- Signal: Trading signal from strategy
- Order: Order to be executed
- Fill: Execution confirmation
- Position: Open position in portfolio
- OrderStatus: Order lifecycle states
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional
from uuid import uuid4


class SignalType(Enum):
    """Signal type enumeration."""
    BUY = "BUY"
    SELL = "SELL"


class OrderSide(Enum):
    """Order side enumeration."""
    BUY = "BUY"
    SELL = "SELL"


class OrderType(Enum):
    """Order type enumeration."""
    MARKET = "MARKET"
    LIMIT = "LIMIT"


class OrderStatus(Enum):
    """Order status enumeration."""
    PENDING = "PENDING"
    SUBMITTED = "SUBMITTED"
    PARTIAL_FILL = "PARTIAL_FILL"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


@dataclass
class Signal:
    """
    Trading signal generated by a strategy.
    
    Attributes:
        signal_id: Unique signal identifier
        strategy_name: Name of strategy that generated signal
        ticker: Stock ticker symbol
        signal_type: BUY or SELL
        strength: Signal strength/confidence (0.0 to 1.0)
        timestamp: When signal was generated
    """
    signal_id: str
    strategy_name: str
    ticker: str
    signal_type: SignalType
    strength: float
    timestamp: datetime
    
    @classmethod
    def create(cls, strategy_name: str, ticker: str, signal_type: SignalType, 
               strength: float = 1.0) -> 'Signal':
        """Create a new signal with auto-generated ID."""
        timestamp = datetime.now()
        signal_id = f"SIG_{timestamp.strftime('%Y%m%d%H%M%S')}_{ticker}_{uuid4().hex[:8]}"
        return cls(
            signal_id=signal_id,
            strategy_name=strategy_name,
            ticker=ticker,
            signal_type=signal_type,
            strength=strength,
            timestamp=timestamp
        )


@dataclass
class Order:
    """
    Order to be executed by broker.
    
    Attributes:
        order_id: Unique order identifier
        signal_id: ID of signal that generated this order
        ticker: Stock ticker symbol
        side: BUY or SELL
        quantity: Number of shares
        order_type: MARKET or LIMIT
        status: Current order status
        limit_price: Limit price (for LIMIT orders)
        submitted_at: When order was submitted
        updated_at: Last status update time
        filled_quantity: Total shares filled so far
    """
    order_id: str
    signal_id: str
    ticker: str
    side: OrderSide
    quantity: int
    order_type: OrderType
    status: OrderStatus
    limit_price: Optional[float] = None
    submitted_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    filled_quantity: int = 0
    
    @classmethod
    def create(cls, signal: Signal, quantity: int, 
               order_type: OrderType = OrderType.MARKET,
               limit_price: Optional[float] = None) -> 'Order':
        """Create a new order from a signal."""
        timestamp = datetime.now()
        order_id = f"ORD_{timestamp.strftime('%Y%m%d%H%M%S')}_{uuid4().hex[:8]}"
        
        # Convert signal type to order side
        side = OrderSide.BUY if signal.signal_type == SignalType.BUY else OrderSide.SELL
        
        return cls(
            order_id=order_id,
            signal_id=signal.signal_id,
            ticker=signal.ticker,
            side=side,
            quantity=quantity,
            order_type=order_type,
            status=OrderStatus.PENDING,
            limit_price=limit_price,
            submitted_at=timestamp,
            updated_at=timestamp,
            filled_quantity=0
        )


@dataclass
class Fill:
    """
    Execution confirmation for an order (or part of an order).
    
    Attributes:
        fill_id: Unique fill identifier
        order_id: ID of order being filled
        quantity: Number of shares filled
        price: Execution price per share
        fees: Total fees/commissions for this fill
        timestamp: When fill occurred
    """
    fill_id: str
    order_id: str
    quantity: int
    price: float
    fees: float
    timestamp: datetime
    
    @classmethod
    def create(cls, order: Order, quantity: int, price: float, 
               fees: float = 0.0) -> 'Fill':
        """Create a new fill for an order."""
        timestamp = datetime.now()
        fill_id = f"FILL_{timestamp.strftime('%Y%m%d%H%M%S')}_{uuid4().hex[:8]}"
        return cls(
            fill_id=fill_id,
            order_id=order.order_id,
            quantity=quantity,
            price=price,
            fees=fees,
            timestamp=timestamp
        )


@dataclass
class Position:
    """
    Open position in the portfolio.
    
    Attributes:
        ticker: Stock ticker symbol
        quantity: Number of shares (positive for long, negative for short)
        avg_cost: Average cost per share
        market_value: Current market value
        unrealized_pnl: Unrealized profit/loss
        opened_at: When position was first opened
        last_updated: Last time position was modified
    """
    ticker: str
    quantity: int
    avg_cost: float
    market_value: float = 0.0
    unrealized_pnl: float = 0.0
    opened_at: datetime = field(default_factory=datetime.now)
    last_updated: datetime = field(default_factory=datetime.now)
    
    def update_market_value(self, current_price: float):
        """Update market value and unrealized P&L."""
        self.market_value = self.quantity * current_price
        self.unrealized_pnl = self.market_value - (self.quantity * self.avg_cost)
        self.last_updated = datetime.now()
    
    def add_shares(self, quantity: int, price: float):
        """Add shares to position (or reduce if quantity negative)."""
        if quantity == 0:
            return
        
        # Calculate new average cost
        if (self.quantity > 0 and quantity > 0) or (self.quantity < 0 and quantity < 0):
            # Adding to existing position
            total_cost = (self.quantity * self.avg_cost) + (quantity * price)
            self.quantity += quantity
            self.avg_cost = total_cost / self.quantity if self.quantity != 0 else 0
        else:
            # Reducing or reversing position
            self.quantity += quantity
            if self.quantity == 0:
                self.avg_cost = 0
            elif abs(quantity) > abs(self.quantity):
                # Position reversed
                self.avg_cost = price
        
        self.last_updated = datetime.now()
    
    def close_position(self):
        """Mark position as closed."""
        self.quantity = 0
        self.market_value = 0.0
        self.unrealized_pnl = 0.0
        self.last_updated = datetime.now()

